[workspace]
members = ["bin/cdp_stuff", "crates/cdp"]
default-members = ["bin/cdp_stuff"]

# Like release, but with full debug symbols. Useful for e.g. `perf`.
[profile.debug-fast]
inherits = "release"
debug = true
