[package]
name = "chromedriver-memes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.94"
thirtyfour = "0.32.0-rc.6"
tokio = { version = "1.26.0", features = ["full"] }
