[package]
name = "chromedriver-memes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
headless_chrome = { git = "https://github.com/rust-headless-chrome/rust-headless-chrome" }
anyhow = "1.0.69"
