[package]
name = "cdp_stuff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
cdp = { path = "../../crates/cdp" }
serde_json = "1.0.94"
anyhow = "1.0.69"
env_logger = "0.10.0"
log = "0.4.17"
